### ISSUE TITLE
@Component and ng1 dependencies?

### ISSUE THREAD

**Issue by j-walker23** [tolemac/Ng2Emulation#2]
Hey, first i love this idea. Especially with holding references to services/components to bootstrap all at once.

I have tried this decorator approach before where i create one angular module and then each decorator registers a `directive` or `service` and it becomes a race condition nightmare with angulars DI system.

Anyway, my question has to do with injecting any services that are external and can not be registered with `@Inject`.

For example in my `AppComponent` i have `$rootScope` and `$state` in the constructor. These will never be injected because of how the component decorator overrides the constructor of the target class.

I was wondering if you had un-written solutions for the old DI, or some other way to use this that i just missed.

Lastly, if i comment out the internals of the `Component` decorator and just assign `$componentMetadata` and `$services` to `target`, then when angular initializes the components class,
all services, angulars and mine using `@Inject` are injected into the constructor

**Comment by tolemac** [comment]
Hi @j-walker23 , at the first hand thank you for your interest in the project.

Indeed, you can not do. The current sources has two days old, after upload it I I thought to public the project to have some feedback, several persons ask me if I knew **ng-forward**: https://github.com/ngUpgraders/ng-forward

They had the same idea 5 months before me and they have the project in a good status.
They haven't @Inject decorator for constructor parameters but you can use it as class decorator.

I recommend you use ng-forward. I want to collaborate with ng-forward writing @Inject for constructor parameter but I have to learn a little of npm.

Best regards.

**Comment by tolemac** [comment]
@j-walker23 at the moment I have decided to follow with the project.
I will explain the reasons ASAP.

Now, you can include ng1 dependencies to the component this way:

``` typescript
constructor(
                @Inject("$parse") $parse: ng.IParseService,
                @Inject("$element") public $element: JQuery,
                @Inject("$attrs") $attrs: ng.IAttributes,
                @Inject("$scope") public $scope: ng.IScope) 
{
}
```

And you can use $inject if you need, the constructor is not override now.

Thanks!
